@echo on

@rem sed -i "s/20240722.0.bcr.2/20250512.1/" MODULE.bazel
@rem if errorlevel 1 exit 1

:: Delegate to the Unixy script. We need to translate the key path variables
:: to be Unix-y rather than Windows-y, though.
set "saved_recipe_dir=%RECIPE_DIR%"
set "saved_source_dir=%SRC_DIR%"

FOR /F "delims=" %%i IN ('cygpath.exe -u "%PYTHON%"') DO set "BAZEL_PYTHON=%%i"
FOR /F "delims=" %%i IN ('cygpath.exe -u "%LIBRARY_PREFIX%\usr\bin\bash.exe"') DO set "BAZEL_SH=%%i"

:: FOR /F "delims=" %%i IN ('cygpath.exe -u -p "%PATH%"') DO set "PATH_OVERRIDE=%%i"
FOR /F "delims=" %%i IN ('cygpath.exe -u "%LIBRARY_PREFIX%"') DO set "LIBRARY_PREFIX=%%i"
FOR /F "delims=" %%i IN ('cygpath.exe -u "%PREFIX%"') DO set "PREFIX=%%i"
FOR /F "delims=" %%i IN ('cygpath.exe -u "%PYTHON%"') DO set "PYTHON=%%i"
FOR /F "delims=" %%i IN ('cygpath.exe -u "%RECIPE_DIR%"') DO set "RECIPE_DIR=%%i"
FOR /F "delims=" %%i IN ('cygpath.exe -u "%SP_DIR%"') DO set "SP_DIR=%%i"
FOR /F "delims=" %%i IN ('cygpath.exe -u "%SRC_DIR%"') DO set "SRC_DIR=%%i"
FOR /F "delims=" %%i IN ('cygpath.exe -u "%STDLIB_DIR%"') DO set "STDLIB_DIR=%%i"
FOR /F "delims=" %%i IN ('cygpath.exe -u "%JAVA_HOME%"') DO set "JAVA_HOME=%%i"

:: Need a very short TMPDIR otherwise we hit the max path limit while compiling bazel
FOR /F "delims=" %%i IN ('cygpath.exe -u "%SYSTEMDRIVE%\t"') DO set "TMPDIR=%%i"
FOR /F "delims=" %%i IN ('cygpath.exe -u "%SYSTEMDRIVE%\t"') DO set "TEMP=%%i"

set MSYSTEM=MINGW%ARCH%
set MSYS2_PATH_TYPE=inherit
set CHERE_INVOKING=1
set "BAZEL_VC=%VSINSTALLDIR%VC"
set "BAZEL_VS=%VSINSTALLDIR%"
set "EXTRA_BAZEL_ARGS=--tool_java_runtime_version=local_jdk --java_runtime_version=local_jdk --host_javabase=@local_jdk//:jdk"

:: We need to unset some environment variables to make the java command line short enough
set AGENT_CLOUDID=
set AGENT_DISABLELOGPLUGIN_TESTFILEPUBLISHERPLUGIN=
set AGENT_DISABLELOGPLUGIN_TESTRESULTLOGPLUGIN=
set AGENT_ENABLE_PIPELINEARTIFACT_LARGE_CHUNK_SIZE=
set AGENT_HOMEDIRECTORY=
set AGENT_ID=
set AGENT_ISSELFHOSTED=
set AGENT_JOBNAME=
set AGENT_JOBSTATUS=
set AGENT_LOGTOBLOBSTORAGESERVICE=
set AGENT_MACHINENAME=
set AGENT_NAME=
set AGENT_OS=
set AGENT_OSARCHITECTURE=
set AGENT_READONLYVARIABLES=
set AGENT_RETAINDEFAULTENCODING=
set AGENT_ROOTDIRECTORY=
set AGENT_SERVEROMDIRECTORY=
set AGENT_TASKRESTRICTIONSENFORCEMENTMODE=
set AGENT_TEMPDIRECTORY=
set AGENT_TOOLSDIRECTORY=
set AGENT_USEWORKSPACEID=
set AGENT_VERSION=
set AGENT_WORKFOLDER=
set ANDROID_HOME=
set ANDROID_NDK=
set ANDROID_NDK_HOME=
set ANDROID_NDK_LATEST_HOME=
set ANDROID_NDK_PATH=
set ANDROID_NDK_ROOT=
set ANDROID_SDK_ROOT=
set ANT_HOME=
set AZURE_CONFIG_DIR=
set AZURE_DEVOPS_CACHE_DIR=
set AZURE_DEVOPS_EXT_CONFIG_DIR=
set AZURE_EXTENSION_DIR=
set AZURE_HTTP_USER_AGENT=
set AZP_75787_ENABLE_COLLECT=
set AZP_75787_ENABLE_NEW_LOGIC=
set AZP_75787_ENABLE_NEW_LOGIC_LOG=
set AZP_75787_ENABLE_NEW_PH_LOGIC=
set AZP_AGENT_CHECK_FOR_TASK_DEPRECATION=
set AZP_AGENT_IGNORE_VSTSTASKLIB=
set AZP_AGENT_LOG_TASKNAME_IN_USERAGENT=
set AZP_AGENT_MOUNT_WORKSPACE=
set AZP_ENABLE_RESOURCE_MONITOR_DEBUG_OUTPUT=
set AZP_PS_ENABLE_INVOKE_PROCESS=
set BUILD_ARTIFACTSTAGINGDIRECTORY=
set BUILD_BINARIESDIRECTORY=
set BUILD_BUILDID=
set BUILD_BUILDNUMBER=
set BUILD_BUILDURI=
set BUILD_CONTAINERID=
set BUILD_DEFINITIONFOLDERPATH=
set BUILD_DEFINITIONNAME=
set BUILD_DEFINITIONVERSION=
set BUILD_QUEUEDBY=
set BUILD_QUEUEDBYID=
set BUILD_REASON=
set BUILD_REPOSITORY_CLEAN=
set BUILD_REPOSITORY_GIT_SUBMODULECHECKOUT=
set BUILD_REPOSITORY_ID=
set BUILD_REPOSITORY_LOCALPATH=
set BUILD_REPOSITORY_NAME=
set BUILD_REPOSITORY_PROVIDER=
set BUILD_REPOSITORY_URI=
set BUILD_REQUESTEDFOR=
set BUILD_REQUESTEDFOREMAIL=
set BUILD_REQUESTEDFORID=
set BUILD_SOURCEBRANCH=
set BUILD_SOURCEBRANCHNAME=
set BUILD_SOURCESDIRECTORY=
set BUILD_SOURCEVERSION=
set BUILD_SOURCEVERSIONAUTHOR=
set BUILD_SOURCEVERSIONMESSAGE=
set BUILD_STAGINGDIRECTORY=
set CHOCOLATEYINSTALL=
set CHROMEWEBDRIVER=
set COMPUTERNAME=
set DISTRIBUTEDTASK_AGENT_ADDFORCECREDENTIALSTOGITCHECKOUT=
set DISTRIBUTEDTASK_AGENT_AGENTENABLEPIPELINEARTIFACTLARGECHUNKSIZE=
set DISTRIBUTEDTASK_AGENT_CHECKIFTASKNODERUNNERISDEPRECATED246=
set DISTRIBUTEDTASK_AGENT_CONTINUEAFTERCANCELPROCESSTREEKILLATTEMPT=
set DISTRIBUTEDTASK_AGENT_DOCKERACTIONRETRIES=
set DISTRIBUTEDTASK_AGENT_ENABLEADDITIONALMASKINGREGEXES=
set DISTRIBUTEDTASK_AGENT_ENABLEISSUESOURCEVALIDATION=
set DISTRIBUTEDTASK_AGENT_ENABLERESOURCEMONITORDEBUGOUTPUT=
set DISTRIBUTEDTASK_AGENT_ENABLERESOURCEUTILIZATIONWARNINGS=
set DISTRIBUTEDTASK_AGENT_FAILDEPRECATEDBUILDTASK=
set DISTRIBUTEDTASK_AGENT_FAILDEPRECATEDTASK=
set DISTRIBUTEDTASK_AGENT_FAILJOBWHENAGENTDIES=
set DISTRIBUTEDTASK_AGENT_FIXPOSSIBLEGITOUTOFMEMORYPROBLEM=
set DISTRIBUTEDTASK_AGENT_FORCEUPDATETOLATEST2VERSION=
set DISTRIBUTEDTASK_AGENT_IGNOREVSTSTASKLIB=
set DISTRIBUTEDTASK_AGENT_LOGTASKNAMEINUSERAGENT=
set DISTRIBUTEDTASK_AGENT_LOGTOBLOBSTORAGESERVICE=
set DISTRIBUTEDTASK_AGENT_MOUNTWORKSPACE=
set DISTRIBUTEDTASK_AGENT_READONLYVARIABLES=
set DISTRIBUTEDTASK_AGENT_ROSETTA2WARNING=
set DISTRIBUTEDTASK_AGENT_USEDOCKERCOMPOSEV2COMPATIBLEMODE=
set DISTRIBUTEDTASK_AGENT_USEFETCHFILTERINCHECKOUTTASK=
set DISTRIBUTEDTASK_AGENT_USEGITLONGPATHS=
set DISTRIBUTEDTASK_AGENT_USELATESTGITVERSION=
set DISTRIBUTEDTASK_AGENT_USEMSALLIBRARY=
set DISTRIBUTEDTASK_AGENT_USENEWNODEHANDLERTELEMETRY=
set DISTRIBUTEDTASK_AGENT_USENODE20TOSTARTCONTAINER=
set DISTRIBUTEDTASK_AGENT_USESPARSECHECKOUTINCHECKOUTTASK=
set DISTRIBUTEDTASK_AGENT_USEWORKSPACEID=
set DISTRIBUTEDTASK_TASKS_COPYFILESOVERSSHV0USEQUEUE=
set DISTRIBUTEDTASK_TASKS_HIDEDOCKEREXECTASKLOGISSUEERROROUTPUT=
set DISTRIBUTEDTASK_TASKS_MODIFYNUMBEROFRETRIESINROBOCOPY=
set DISTRIBUTEDTASK_TASKS_NODE_SKIPDEBUGLOGSWHENDEBUGMODEOFF=
set DISTRIBUTEDTASK_TASKS_RETIREAZURERMPOWERSHELLMODULE=
set DISTRIBUTEDTASK_TASKS_SKIPHELMMANIFESTNULLPARTS=
set DISTRIBUTEDTASK_TASKS_USEDIGESTIMAGEFROMFILE=
set DISTRIBUTEDTASK_TASKS_USELATESTOPENSSLVERSION=
set DOTNET_MULTILEVEL_LOOKUP=
set DOTNET_NOLOGO=
set DOTNET_SKIP_FIRST_TIME_EXPERIENCE=
set EDGEWEBDRIVER=
set FSHARPINSTALLDIR=
set GECKOWEBDRIVER=
set GOROOT_1_19_X64=
set GOROOT_1_20_X64=
set GOROOT_1_21_X64=
set GOROOT_1_22_X64=
set GOROOT_1_23_X64=
set GOROOT_1_24_X64=
set JAVA_HOME_11_X64=
set JAVA_HOME_17_X64=
set JAVA_HOME_21_X64=
set JAVA_HOME_8_X64=
set LUA_VER=
set NPY_VER=
set PIPX_BIN_DIR=
set PIPX_HOME=
set PIP_CACHE_DIR=
set PIP_IGNORE_INSTALLED=
set PIP_NO_BUILD_ISOLATION=
set PIP_NO_DEPENDENCIES=
set PIP_NO_INDEX=
set PROCESSOR_IDENTIFIER=
set PROCESSOR_REVISION=
set PSMODULEANALYSISCACHEPATH=
set PSMODULEPATH=
set PY3K=
set PYTHONNOUSERSITE=
set PYTHONUNBUFFERED=
set PY_VCRUNTIME_REDIST=
set PY_VER=
set ROSETTA2_WARNING=
set RTOOLS43_HOME=
set RTOOLS44_HOME=
set RTOOLS45_HOME=
set R_VER=
set SBT_HOME=
:: show remaining environment variables, in case the list grows enough
:: to run into "/lib/jvm/bin/java: Argument list too long" again.
set

set "BAZEL_BUILD_OPTS=--cxxopt=/std:c++17"
bash -lx ./compile.sh
if errorlevel 1 exit 1

copy output\bazel.exe %LIBRARY_BIN%\
