{% set version = "8.3.1" %}
{% set base_url = "https://github.com/bazelbuild/bazel/releases/download" %}

package:
  name: bazel
  version: {{ version }}

source:
  - url: {{ base_url }}/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: 79da863df05fa4de79a82c4f9d4e710766f040bc519fd8b184a4d4d51345d5ba
    patches:
      ## bazel depends on https://github.com/conda-forge/singlejar-feedstock to build,
      ## which patches the same sources; the patches from singlejar should either be
      ## taken over here, or synced back if change is necessary
      - patches/0001-allow-args-to-be-passed-to-bazel_build.patch
      - patches/0002-Build-with-native-dependencies.patch         # [unix]
      - patches/0003-use-C-17.patch
      - patches/0004-Use-conda-packages-for-build-tools.patch     # [unix]
      - patches/0005-grpc-java-plugin-from-build.patch            # [unix]
      - patches/0006-bazel-bin-loader-path.patch                  # [osx]
      - patches/0007-Adjust-cross-bazel-resultpath.patch
      - patches/0008-win-Disable-VS-activation-and-make-build-verbose.patch
      - patches/0009-Install-protobuf-via-maven.patch             # [unix]
      - patches/0010-Adopt-system-libprotobuf.patch               # [unix]
      - patches/0011-Enable-new-protobuf-major-release.patch      # [unix]
      - patches/0012-Add-missing-absl-dependency.patch

build:
  number: 0
  ignore_prefix_files: true
  binary_relocation: false
  # We are currently unable to select a JDK toolchain for the build.
  # This can be re-enabled once someone finds the correct option.
  skip: true  # [ppc64le]
  skip: true  # [not win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sed                      # [unix]
    - m2-sed                   # [win]
    - openjdk 21.*             # [unix]
    # we need $BUILD_PREFIX/bin/{grpc_cpp_plugin,grpc_java_plugin,protoc}
    # bazel vendors & expects quite an old grpc-java-plugin; avoid pulling in versions with
    # https://github.com/grpc/grpc-java/commit/ea8c31c305eac5a6ac9a09de5ea2edb9ed719a31
    - grpc_java_plugin <1.70   # [unix]
    - libgrpc                  # [unix]
    - libprotobuf              # [unix]
    - ijar {{ version }}       # [unix]
    - singlejar {{ version }}  # [unix]
    - bazel-toolchain >=0.2.0  # [unix]
    - zip                      # [linux]
    - unzip                    # [linux]
    - python *                 # [win]
  host:
    - libabseil             # [unix]
    - libgrpc               # [unix]
    - libprotobuf           # [unix]
    - protobuf-bazel-rules  # [unix]
    - openjdk 21.*          # [win]
    - posix                 # [win]
  run:
    - openjdk >=21
    - posix                    # [win]
    - ijar {{ version }}       # [unix]
    - singlejar {{ version }}  # [unix]

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain >=0.2  # [unix]
  commands:
    - bazel -h
    - bazel version

about:
  home: https://bazel.build/
  summary: a fast, scalable, multi-language and extensible build system
  dev_url: https://github.com/bazelbuild/bazel
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - h-vetinari
    - nehaljwani
    - abhi18av
    - jschueller
    - adrianchia
    - xhochy
