{% set version = "5.1.1" %}

package:
  name: bazel
  version: {{ version }}

source:
  url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel-{{ version }}-dist.zip
  sha256: 7f5d3bc1d344692b2400f3765fd4b5c0b636eb4e7a8a7b17923095c7b56a4f78
  patches:
    - 0001-allow-args-to-be-passed-to-bazel_build.patch
    - 0002-Build-with-native-dependencies.patch  # [unix]
    - 0003-Parametrize-LIBPROTOBUF_VERSION.patch  # [unix]
    - 0004-Use-conda-packages-for-build-tools.patch  # [build_platform != target_platform]
    - 0005-grpc-java-plugin-from-build.patch  # [unix]
    - 0006-bazel-bin-loader-path.patch  # [osx]
    - 0007-Adjust-cross-bazel-resultpath.patch  # [build_platform != target_platform]
    - 0008-win-Disable-VS-activation-and-make-build-verbose.patch

build:
  number: 4
  ignore_prefix_files: true
  binary_relocation: false
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ feature_set }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sed                      # [unix]
    - openjdk >=8              # [unix]
    - grpc-cpp                 # [unix]
    # Remove this pin again once the java parts of bazel can build with a newer gRPC
    - grpc_java_plugin 1.37    # [unix and feature_set == "jdk"]
    # - grpc_java_plugin {{ grpc_cpp }}  # [unix]
    - libprotobuf              # [unix]
    - ijar {{ version }}       # [build_platform != target_platform]
    - singlejar {{ version }}  # [build_platform != target_platform]
    - bazel-toolchain          # [unix]
    - zip                      # [linux]
    - unzip                    # [linux]
  host:
    - abseil-cpp  # [unix]
    - grpc-cpp  # [unix]
    - libprotobuf  # [unix]
    - openjdk >=8  # [win]
    - posix  # [win]
  run:
    - openjdk >=8
    - posix  # [win]
    - ijar {{ version }}   # [build_platform != target_platform]
    - singlejar {{ version }}   # [build_platform != target_platform]

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  commands:
    - bazel -h
    - bazel version

about:
  home: https://www.bazel.io/
  summary: build system originally authored by Google
  description: |
    Bazel is Google's own build tool, now publicly available in Beta. Bazel has
    built-in support for building both client and server software, including
    client applications for both Android and iOS platforms. It also provides an
    extensible framework that you can use to develop your own build rules.
  dev_url: https://github.com/bazelbuild/bazel
  doc_url: https://www.bazel.io/versions/master/docs/install.html
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nehaljwani
    - abhi18av
    - jschueller
    - adrianchia
    - xhochy
