{% set version = "6.2.1" %}

package:
  name: bazel
  version: {{ version }}

source:
  url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel-{{ version }}-dist.zip
  sha256: 4cf4d264bff388ee0012735728630d23832d3c9d021383b2fadceadb0775dd6b
  patches:
    - patches/0001-allow-args-to-be-passed-to-bazel_build.patch
    - patches/0002-Build-with-native-dependencies.patch      # [unix]
    # This patch ensures that the relevant version of protobuf-java matches libprotobuf.
    # Note that "relevant" here means minor.patch, where minor is based on the last two
    # digits of the calendar year. The major version may be different per language, see
    # https://protobuf.dev/support/version-support/
    # If the java major version changes, it needs to be bumped manually in build.sh.
    - patches/0003-Match-version-of-protobuf-java-with-libprotobuf.patch       # [unix]
    - patches/0004-Use-conda-packages-for-build-tools.patch  # [build_platform != target_platform]
    - patches/0005-grpc-java-plugin-from-build.patch         # [unix]
    - patches/0006-bazel-bin-loader-path.patch               # [osx]
    - patches/0007-Adjust-cross-bazel-resultpath.patch       # [build_platform != target_platform]
    - patches/0008-win-Disable-VS-activation-and-make-build-verbose.patch
    # backport https://github.com/bazelbuild/bazel/pull/18608 (squashed; as of 2023-06-24)
    - patches/0009-Update-windows-VS-detection-code-to-account-for-new-.patch

build:
  number: 1
  ignore_prefix_files: true
  binary_relocation: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sed                      # [unix]
    - openjdk >=8              # [unix]
    # we need $BUILD_PREFIX/bin/{grpc_cpp_plugin,grpc_java_plugin,protoc}
    - grpc_java_plugin         # [unix]
    - libgrpc                  # [unix]
    - libprotobuf              # [unix]
    - ijar {{ version }}       # [build_platform != target_platform]
    - singlejar {{ version }}  # [build_platform != target_platform]
    - bazel-toolchain          # [unix]
    - zip                      # [linux]
    - unzip                    # [linux]
    - python *                 # [win]
  host:
    - libabseil        # [unix]
    - libgrpc          # [unix]
    - libprotobuf      # [unix]
    - openjdk >=8      # [win]
    - posix            # [win]
  run:
    - openjdk >=8
    - posix                    # [win]
    - ijar {{ version }}       # [build_platform != target_platform]
    - singlejar {{ version }}  # [build_platform != target_platform]

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  commands:
    - bazel -h
    - bazel version

about:
  home: https://bazel.build/
  summary: a fast, scalable, multi-language and extensible build system
  dev_url: https://github.com/bazelbuild/bazel
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - h-vetinari
    - nehaljwani
    - abhi18av
    - jschueller
    - adrianchia
    - xhochy
