{% set version = "9.0.2" %}
{% set base_url = "https://github.com/bazelbuild/bazel/releases/download" %}

package:
  name: bazel
  version: {{ version }}

source:
  - url: {{ base_url }}/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: d80b8f708e7a5840fd09b853a4343cace7e4c3504d4e8ac67367d4cb6224436e
    patches:
      # bazel depends on https://github.com/conda-forge/singlejar-feedstock to build,
      # which patches the same sources; the patches from singlejar should either be
      # taken over here, or synced back if change is necessary
      - patches/0001-allow-args-to-be-passed-to-bazel_build.patch                # [unix]
      - patches/0002-use-C-17.patch                                              # [unix]
      - patches/0003-Use-conda-packages-for-build-tools.patch                    # [unix]
      - patches/0004-grpc-java-plugin-from-build.patch                           # [unix]
      - patches/0005-bazel-bin-loader-path.patch                                 # [osx]
      - patches/0006-Adjust-cross-bazel-resultpath.patch                         # [unix]
      - patches/0007-avoid-linking-to-grpc-_unsecure-use-regular-variant-.patch  # [unix]
      - patches/0008-Build-with-native-dependencies.patch                        # [unix]

  - url: {{ base_url }}/{{ version }}/bazel-{{ version }}-windows-x86_64.exe  # [win]
    sha256: e45277210da3fc1999e474edce5d9e73b37a6fdc0b78418880d9adad12276c4e  # [win]

build:
  number: 0
  ignore_prefix_files: true
  binary_relocation: false
  # We are currently unable to select a JDK toolchain for the build.
  # This can be re-enabled once someone finds the correct option.
  skip: true  # [ppc64le]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m2-sed                   # [win]
    - sed                      # [unix]
    - openjdk 21.*             # [unix]
    # we need $BUILD_PREFIX/bin/{grpc_cpp_plugin,grpc_java_plugin,protoc}
    - grpc_java_plugin         # [unix]
    - libgrpc                  # [unix]
    - libprotobuf              # [unix]
    - ijar {{ version }}       # [unix]
    - singlejar {{ version }}  # [unix]
    - bazel-toolchain >=0.5.1  # [unix]
    - zip                      # [linux]
    - unzip                    # [linux]
    - python *                 # [win]
  host:
    - libabseil             # [unix]
    - libgrpc               # [unix]
    - libprotobuf           # [unix]
    - protobuf-bazel-rules  # [unix]
    - grpc-bazel-rules      # [unix]
    - openjdk 21.*          # [win]
    - posix                 # [win]
  run:
    - openjdk >=21
    - posix                    # [win]
    - ijar {{ version }}       # [unix]
    - singlejar {{ version }}  # [unix]

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain >=0.5.1  # [unix]
  commands:
    - bazel -h
    - bazel version

about:
  home: https://bazel.build/
  summary: a fast, scalable, multi-language and extensible build system
  dev_url: https://github.com/bazelbuild/bazel
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - h-vetinari
    - nehaljwani
    - abhi18av
    - jschueller
    - adrianchia
    - xhochy
