{% set version = "4.1.0" %}

package:
  name: bazel
  version: {{ version }}

source:
  url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel-{{ version }}-dist.zip
  sha256: f377d755c96a50f6bd2f423562598d822f43356783330a0b780ad442864d6eeb
  patches:
    - 0001-allow-args-to-be-passed-to-bazel_build.patch
    - 0002-linux-sandbox-don-t-assume-lrt-D__STDC_FORMAT_MACROS.patch  # [linux]
    - 0003-Build-with-native-dependencies.patch  # [unix]
    - 0004-zipper-from-conda-package.patch  # [build_platform != target_platform]
    - 0005-grpc-java-plugin-build.patch     # [build_platform != target_platform]
    - 0006-bazel-bin-loader-path.patch      # [osx]
    - 0007-link-libprotobuf-grpc-java.patch  # [build_platform == target_platform]
    - 0008-adjust-cross-bazel-resultpath.patch  # [build_platform != target_platform]

build:
  number: 0
  ignore_prefix_files: true
  binary_relocation: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sed               # [unix]
    - openjdk >=8       # [unix]
    - grpc-cpp          # [unix]
    - grpc_java_plugin  # [osx]
    - libprotobuf       # [unix]
    - ijar              # [build_platform != target_platform]
  host:
    - grpc-cpp  # [unix]
    - libprotobuf  # [unix]
    - openjdk >=8  # [win]
    - unzip  # [linux]
    - zip  # [linux]
    - posix  # [win]
  run:
    - openjdk >=8
    - posix  # [win]
    - ijar  # [build_platform != target_platform]

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  commands:
    - bazel -h
    - bazel version

about:
  home: https://www.bazel.io/
  summary: build system originally authored by Google
  description: |
    Bazel is Google's own build tool, now publicly available in Beta. Bazel has
    built-in support for building both client and server software, including
    client applications for both Android and iOS platforms. It also provides an
    extensible framework that you can use to develop your own build rules.
  dev_url: https://github.com/bazelbuild/bazel
  doc_url: https://www.bazel.io/versions/master/docs/install.html
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nehaljwani
    - abhi18av
    - jschueller
    - adrianchia
    - xhochy
