{% set version = "0.12.0" %}

package:
  name: bazel
  version: {{ version }}

source:
  url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel-{{ version }}-dist.zip
  sha256: 3b3e7dc76d145046fdc78db7cac9a82bc8939d3b291e53a7ce85315feb827754
  patches:
    - xcode_locator.patch  # [osx]

build:
  number: 0
  ignore_prefix_files: True
  binary_relocation: False
  skip: True  # [win]

requirements:
  build:
    - openjdk >=8
    - unzip  # [linux]
    - zip    # [linux]
  run:
    - openjdk >=8

test:
  commands:
    - bazel -h

about:
  home: https://www.bazel.io/
  summary: build system originally authored by Google
  description: |
    Bazel is Google's own build tool, now publicly available in Beta. Bazel has
    built-in support for building both client and server software, including
    client applications for both Android and iOS platforms. It also provides an
    extensible framework that you can use to develop your own build rules.
  dev_url: https://github.com/bazelbuild/bazel
  doc_url: https://www.bazel.io/versions/master/docs/install.html
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jjhelmus
    - nehaljwani
    - abhi18av
