{% set version = "8.3.1" %}
{% set base_url = "https://github.com/bazelbuild/bazel/releases/download" %}

package:
  name: bazel
  version: {{ version }}

source:
  - url: {{ base_url }}/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: 79da863df05fa4de79a82c4f9d4e710766f040bc519fd8b184a4d4d51345d5ba
    patches:
      # - patches/0002-win-Disable-VS-activation-and-make-build-verbose.patch
  - url: {{ base_url }}/{{ version }}/bazel-{{ version }}-windows-x86_64.exe  # [win]
    sha256: a3349d1d9e2327e03344c47244d4832ab14fc78142d050aa5599d85ee26b5f79  # [win]

build:
  number: 0
  ignore_prefix_files: true
  binary_relocation: false
  # We are currently unable to select a JDK toolchain for the build.
  # This can be re-enabled once someone finds the correct option.
  skip: true  # [ppc64le]
  skip: true  # [not win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sed                      # [unix]
    - m2-sed                   # [win]
    - openjdk 21.*             # [unix]
    # we need $BUILD_PREFIX/bin/{grpc_cpp_plugin,grpc_java_plugin,protoc}
    # bazel vendors & expects quite an old grpc-java-plugin; avoid pulling in versions with
    # https://github.com/grpc/grpc-java/commit/ea8c31c305eac5a6ac9a09de5ea2edb9ed719a31
    - grpc_java_plugin <1.70   # [unix]
    - libgrpc                  # [unix]
    - libprotobuf              # [unix]
    - ijar {{ version }}       # [unix]
    - singlejar {{ version }}  # [unix]
    - bazel-toolchain >=0.2.0  # [unix]
    - zip                      # [linux]
    - unzip                    # [linux]
    - python *                 # [win]
  host:
    - libabseil             # [unix]
    - libgrpc               # [unix]
    - libprotobuf           # [unix]
    - protobuf-bazel-rules  # [unix]
    - openjdk 21.*          # [win]
    - posix                 # [win]
  run:
    - openjdk >=21
    - posix                    # [win]
    - ijar {{ version }}       # [unix]
    - singlejar {{ version }}  # [unix]

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain >=0.2  # [unix]
  commands:
    - bazel -h
    - bazel version

about:
  home: https://bazel.build/
  summary: a fast, scalable, multi-language and extensible build system
  dev_url: https://github.com/bazelbuild/bazel
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - h-vetinari
    - nehaljwani
    - abhi18av
    - jschueller
    - adrianchia
    - xhochy
