{% set version = "4.2.2" %}

package:
  name: bazel
  version: {{ version }}

source:
  url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel-{{ version }}-dist.zip
  sha256: 9981d0d53a356c4e87962847750a97c9e8054e460854748006c80f0d7e2b2d33
  patches:
    - 0001-allow-args-to-be-passed-to-bazel_build.patch
    - 0003-Build-with-native-dependencies.patch   # [unix]
    - 0001-Parametrize-LIBPROTOBUF_VERSION.patch  # [unix]
    - 0004-zipper-from-conda-package.patch        # [build_platform != target_platform]
    - 0005-grpc-java-plugin-build.patch           # [unix]
    - 0006-bazel-bin-loader-path.patch            # [osx]
    - 0008-adjust-cross-bazel-resultpath.patch    # [build_platform != target_platform]
    - 0009-Omit-duplicate-codesign.patch          # [osx]
    - 0010-win-Disable-VS-activation-and-make-build-verbose.patch

build:
  number: 12
  ignore_prefix_files: true
  binary_relocation: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sed               # [unix]
    - openjdk >=8,<17   # [unix]
    - grpc-cpp {{ grpc_cpp }}  # [unix]
    - grpc_java_plugin 1.37    # [unix]
    - libprotobuf       # [unix]
    - ijar              # [build_platform != target_platform]
    - bazel-toolchain   # [unix]
    - zip               # [linux]
    - unzip             # [linux]
    - python *          # [win]
  host:
    - libabseil  # [unix]
    - grpc-cpp  # [unix]
    - libprotobuf  # [unix]
    - openjdk >=8,<17  # [win]
    - posix  # [win]
  run:
    - openjdk >=8,<17
    - posix  # [win]
    - ijar  # [build_platform != target_platform]

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  commands:
    - bazel -h
    - bazel version

about:
  home: https://www.bazel.io/
  summary: build system originally authored by Google
  description: |
    Bazel is Google's own build tool, now publicly available in Beta. Bazel has
    built-in support for building both client and server software, including
    client applications for both Android and iOS platforms. It also provides an
    extensible framework that you can use to develop your own build rules.
  dev_url: https://github.com/bazelbuild/bazel
  doc_url: https://www.bazel.io/versions/master/docs/install.html
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nehaljwani
    - abhi18av
    - jschueller
    - adrianchia
    - xhochy
