{% set version = "2.1.0" %}

package:
  name: bazel
  version: {{ version }}

source:
  url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel-{{ version }}-dist.zip
  sha256: 3371cd9050989173a3b27364668328653a65653a50a85c320adc53953b4d5f46
  patches:
    - 0001-allow-args-to-be-passed-to-bazel_build.patch
   #- 0005-Use-LSFindApplicationForInfo-for-locating-xcode.patch

build:
  number: 1
  ignore_prefix_files: True
  binary_relocation: False
  # libstdc++: statically linked
  ignore_run_exports:  # [not osx]
    - libstdcxx-ng  # [not osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - openjdk >=8
    - unzip
    - zip
  run:
    - openjdk >=8

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  commands:
    - bazel -h
    - bazel version
    # libstdc++ should not be included in this listing as it is statically linked
    - readelf -d $PREFIX/bin/bazel  # [linux]

about:
  home: https://www.bazel.io/
  summary: build system originally authored by Google
  description: |
    Bazel is Google's own build tool, now publicly available in Beta. Bazel has
    built-in support for building both client and server software, including
    client applications for both Android and iOS platforms. It also provides an
    extensible framework that you can use to develop your own build rules.
  dev_url: https://github.com/bazelbuild/bazel
  doc_url: https://www.bazel.io/versions/master/docs/install.html
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jjhelmus
    - nehaljwani
    - abhi18av
