build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  # linux_aarch64: linux_aarch64
  # linux_ppc64le: linux_ppc64le
  osx_arm64: osx_64
conda_forge_output_validation: true
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
test: native
os_version:
  linux_64: cos7
