# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: toml -*-

#                             VVVVVV  minimum `pixi` version
"$schema" = "https://pixi.sh/v0.36.0/schema/manifest/schema.json"

[project]
name = "bazel-feedstock"
version = "3.51.1"  # conda-smithy version used to generate this file
description = "Pixi configuration for conda-forge/bazel-feedstock"
authors = ["@conda-forge/bazel"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
python = "3.12.*"

[tasks]
[tasks.inspect-all]
cmd = "inspect_artifacts --all-packages"
description = "List contents of all packages found in conda-build build directory."
[tasks.build]
cmd = "conda-build build recipe"
description = "Build bazel-feedstock directly (without setup scripts), no particular variant specified"
[tasks.debug]
cmd = "conda-build debug recipe"
description = "Debug bazel-feedstock directly (without setup scripts), no particular variant specified"
[tasks."build-win_64_"]
cmd = "conda-build build recipe -m .ci_support/win_64_.yaml --suppress-variables --clobber-file .ci_support/clobber_win_64_.yaml"
description = "Build bazel-feedstock with variant win_64_ directly (without setup scripts)"
[tasks."debug-win_64_"]
cmd = "conda-build debug recipe -m .ci_support/win_64_.yaml"
description = "Debug bazel-feedstock with variant win_64_ directly (without setup scripts)"
[tasks."inspect-win_64_"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_.yaml"
description = "List contents of bazel-feedstock packages built for variant win_64_"

[feature.smithy.dependencies]
conda-smithy = "*"
[feature.smithy.tasks.build-locally]
cmd = "python ./build-locally.py"
description = "Build packages locally using the same setup scripts used in conda-forge's CI"
[feature.smithy.tasks.smithy]
cmd = "conda-smithy"
description = "Run conda-smithy. Pass necessary arguments."
[feature.smithy.tasks.rerender]
cmd = "conda-smithy rerender"
description = "Rerender the feedstock."
[feature.smithy.tasks.lint]
cmd = "conda-smithy lint --conda-forge recipe"
description = "Lint the feedstock recipe"

[environments]
smithy = ["smithy"]
# This is a copy of default, to be enabled by build_steps.sh during Docker builds
# __PLATFORM_SPECIFIC_ENV__ = []
